/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tfm.generador.json.de.historias;

import java.awt.Component;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Juanca
 */
public class Interfaz extends javax.swing.JFrame {

    private int tabs;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();

        setLocationRelativeTo(null);
        setTitle("Generador JSON de historias geolocalizadas Android");

        this.tabs = 1;
        MisionPanel m = new MisionPanel("#1");
        this.tab.add("#1", m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonGuardar = new javax.swing.JButton();
        BotonAnadir = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();
        historia_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldImagenTitulo = new javax.swing.JTextField();
        jTextFieldLatitudInicial = new javax.swing.JTextField();
        jTextFieldZoomInicial = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFieldDescripcion = new javax.swing.JTextArea();
        jTextFieldLongitudInicial = new javax.swing.JTextField();
        ES_EL_PANEL = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        icono = new javax.swing.JTextField();
        latitud = new javax.swing.JTextField();
        longitud = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        precedentes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        codigoTipo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pistaAudio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonGuardar.setText("Guardar historia");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonAnadir.setText("Añadir misión");
        BotonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnadirActionPerformed(evt);
            }
        });

        BotonEliminar.setText("Eliminar misión");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Nombre de la historia");

        jTextFieldTitulo.setText("Buscatesoros UGR");
        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Descripción de la historia");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Imagen de título");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Coordenadas iniciales de la cámara");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("Zoom inicial de la cámara");

        jTextFieldImagenTitulo.setText("titulo");

        jTextFieldLatitudInicial.setText("37.1708");

        jTextFieldZoomInicial.setText("16");

        jTextFieldDescripcion.setColumns(20);
        jTextFieldDescripcion.setRows(5);
        jTextFieldDescripcion.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n\nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n\nExcepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
        jScrollPane2.setViewportView(jTextFieldDescripcion);

        jTextFieldLongitudInicial.setText("-3.607212");

        javax.swing.GroupLayout historia_panelLayout = new javax.swing.GroupLayout(historia_panel);
        historia_panel.setLayout(historia_panelLayout);
        historia_panelLayout.setHorizontalGroup(
            historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historia_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(historia_panelLayout.createSequentialGroup()
                        .addGroup(historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(historia_panelLayout.createSequentialGroup()
                                .addGroup(historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(historia_panelLayout.createSequentialGroup()
                                        .addGroup(historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel10))
                                        .addGap(27, 27, 27)
                                        .addGroup(historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                            .addComponent(jTextFieldImagenTitulo)))
                                    .addGroup(historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, historia_panelLayout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldLatitudInicial))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, historia_panelLayout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldZoomInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLongitudInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                        .addGap(352, 352, 352))))
        );
        historia_panelLayout.setVerticalGroup(
            historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historia_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldImagenTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldLatitudInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLongitudInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(historia_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldZoomInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
        );

        tab.addTab("Historia", historia_panel);

        jLabel2.setText("Nombre");

        jLabel3.setText("Icono");

        jLabel4.setText("Coordenadas");

        jLabel5.setText("Tipo");

        nombre.setText("1");

        icono.setText("2");

        latitud.setText("3");

        longitud.setText("4");
        longitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longitudActionPerformed(evt);
            }
        });

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Precedentes");

        precedentes.setText("5");

        jLabel7.setText("Texto");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        codigoTipo.setText("6");
        codigoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTipoActionPerformed(evt);
            }
        });

        jLabel9.setText("Pista de audio:");

        pistaAudio.setText("7");

        javax.swing.GroupLayout ES_EL_PANELLayout = new javax.swing.GroupLayout(ES_EL_PANEL);
        ES_EL_PANEL.setLayout(ES_EL_PANELLayout);
        ES_EL_PANELLayout.setHorizontalGroup(
            ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ES_EL_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(ES_EL_PANELLayout.createSequentialGroup()
                        .addGroup(ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ES_EL_PANELLayout.createSequentialGroup()
                                .addGroup(ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(26, 26, 26)
                                .addGroup(ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precedentes)
                                    .addComponent(icono, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                    .addComponent(nombre)
                                    .addGroup(ES_EL_PANELLayout.createSequentialGroup()
                                        .addGroup(ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(comboTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(latitud, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(longitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(codigoTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(89, 89, 89)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pistaAudio))
                            .addComponent(jLabel7))
                        .addGap(53, 53, 53))))
        );
        ES_EL_PANELLayout.setVerticalGroup(
            ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ES_EL_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(pistaAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(latitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ES_EL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(precedentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
        );

        tab.addTab("--", ES_EL_PANEL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BotonGuardar)
                .addGap(244, 244, 244)
                .addComponent(BotonAnadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonEliminar)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGuardar)
                    .addComponent(BotonAnadir)
                    .addComponent(BotonEliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnadirActionPerformed
        ++tabs;
        MisionPanel m = new MisionPanel("#" + tabs);
        this.tab.add("#" + tabs, m);
    }//GEN-LAST:event_BotonAnadirActionPerformed

    private void longitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longitudActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        Component[] componentsP = tab.getComponents();
        JSONArray historia = new JSONArray();
        JSONArray arrHistorias = new JSONArray();
        JSONObject titulo = new JSONObject();

        for (int i = 2; i < componentsP.length; i++) {
            try {
                tfm.generador.json.de.historias.MisionPanel jp = (tfm.generador.json.de.historias.MisionPanel) componentsP[i];

                JSONObject coordenadas = new JSONObject();
                coordenadas.put("Longitud", jp.getLongitud());
                coordenadas.put("Latitud", jp.getLatitud());

                JSONObject tip = new JSONObject();
                tip.put("Tipo", jp.getComboTipo());
                tip.put("Codigo", jp.getCodigoTipo());

                Mision m = new Mision(jp.getCodigo(), jp.getNombre(), jp.getIcono(), tip, jp.getTexto(), coordenadas, jp.getPrecedentes(), "QR".equals(jp.getComboTipo()), jp.getPistaAudio());

                arrHistorias.put(m.crearJson());
            } catch (JSONException | IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            titulo.put("Nombre historia", jTextFieldTitulo.getText());
            titulo.put("Descripcion", jTextFieldDescripcion.getText());
            titulo.put("Codigo", jTextFieldTitulo.getText());

            titulo.put("Imagen de titulo", jTextFieldImagenTitulo.getText());
            titulo.put("Zoom inicial", jTextFieldZoomInicial.getText());

            JSONObject coor = new JSONObject();
            coor.put("Latitud inicial", jTextFieldLatitudInicial.getText());
            coor.put("Longitud inicial", jTextFieldLongitudInicial.getText());
            titulo.put("Camara inicial", coor);

            titulo.put("Misiones", "auxStr");
            historia.put(titulo);
        } catch (JSONException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

        int inicio = titulo.toString().indexOf("auxStr");
        int tam = titulo.toString().length();
        String json = titulo.toString().substring(0, inicio - 1) + arrHistorias.toString() + titulo.toString().substring(inicio + 1 + "auxStr".length(), tam);
        //System.out.println(json);
        escribirFichero("fichero.json", json);
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void codigoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTipoActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void escribirFichero(String ficheroN, String texto) {
        System.out.println("escribirFichero: " + texto);
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            fichero = new FileWriter(ficheroN);
            pw = new PrintWriter(fichero);

            pw.println(texto);

        } catch (IOException e) {
        } finally {
            try {
                if (null != fichero) {
                    fichero.close();
                }
            } catch (IOException e2) {
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAnadir;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JPanel ES_EL_PANEL;
    private javax.swing.JTextField codigoTipo;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JPanel historia_panel;
    private javax.swing.JTextField icono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldImagenTitulo;
    private javax.swing.JTextField jTextFieldLatitudInicial;
    private javax.swing.JTextField jTextFieldLongitudInicial;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldZoomInicial;
    private javax.swing.JTextField latitud;
    private javax.swing.JTextField longitud;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pistaAudio;
    private javax.swing.JTextField precedentes;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
